/**
 * Generated by `npm run art:manifest` from the PNG files in public/assets. Do not edit by hand.
 *
 * Keys are paths relative to public/assets without extension ("skins/edecio-samurai"),
 * so the file is served at `/assets/<key>.png`. A key that is missing here means the
 * art does not exist yet and the UI must draw its procedural fallback.
 */

export interface SpriteMeta {
  /** Native size in pixels. Draw at an integer multiple with image-rendering: pixelated. */
  w: number;
  h: number;
  /**
   * Attachment point in native pixels, from the top-left corner.
   * - skins/*: the neck, where the head's chin sits.
   * - heads/*: the chin, which sits on the body's neck.
   * - hats/*: the point of the hat that rests on the top of the head.
   */
  anchor?: { x: number; y: number };
}

export const ASSETS: Record<string, SpriteMeta> = {};
