/**
 * Generated by `npm run art:manifest` from the PNG files in public/assets. Do not edit by hand.
 *
 * Keys are paths relative to public/assets without extension ("skins/edecio-samurai"),
 * so the file is served at `/assets/<key>.png`. A key that is missing here means the
 * art does not exist yet and the UI must draw its procedural fallback.
 */

export interface SpriteMeta {
  /** Native size in pixels. Draw at an integer multiple with image-rendering: pixelated. */
  w: number;
  h: number;
  /**
   * Attachment point in native pixels, from the top-left corner.
   * - skins/*: the neck, where the head's chin sits.
   * - heads/*: the chin, which sits on the body's neck.
   * - hats/*: the point of the hat that rests on the top of the head.
   */
  anchor?: { x: number; y: number };
}

export const ASSETS: Record<string, SpriteMeta> = {
  "heads/angelo": { w: 47, h: 56, anchor: { x: 23, y: 55 } },
  "heads/angelo-paraninfo": { w: 61, h: 63, anchor: { x: 30, y: 62 } },
  "heads/angelo-rei": { w: 51, h: 64, anchor: { x: 25, y: 63 } },
  "heads/b1": { w: 61, h: 56, anchor: { x: 30, y: 52 } },
  "heads/b1-rainha": { w: 62, h: 62, anchor: { x: 31, y: 59 } },
  "heads/b2": { w: 57, h: 58, anchor: { x: 28, y: 50 } },
  "heads/edecio": { w: 47, h: 53, anchor: { x: 23, y: 52 } },
  "heads/edecio-cria": { w: 51, h: 63, anchor: { x: 25, y: 62 } },
  "heads/edecio-full-dima": { w: 50, h: 57, anchor: { x: 25, y: 56 } },
  "heads/edecio-gladiador": { w: 49, h: 76, anchor: { x: 24, y: 75 } },
  "heads/edecio-samurai": { w: 55, h: 70, anchor: { x: 27, y: 69 } },
  "heads/gladimir": { w: 43, h: 52, anchor: { x: 21, y: 51 } },
  "heads/gladimir-maker": { w: 44, h: 52, anchor: { x: 22, y: 51 } },
  "heads/gladimir-mestre": { w: 52, h: 54, anchor: { x: 26, y: 53 } },
  "heads/gladimir-piloto": { w: 51, h: 53, anchor: { x: 25, y: 52 } },
  "heads/guto": { w: 53, h: 56, anchor: { x: 26, y: 55 } },
  "heads/guto-astronauta": { w: 62, h: 58, anchor: { x: 31, y: 57 } },
  "heads/guto-pagodeiro": { w: 69, h: 58, anchor: { x: 34, y: 57 } },
  "heads/pablo": { w: 53, h: 56, anchor: { x: 26, y: 55 } },
  "heads/pablo-mago": { w: 69, h: 69, anchor: { x: 34, y: 68 } },
  "heads/wagner": { w: 42, h: 53, anchor: { x: 21, y: 52 } },
  "heads/wagner-agente": { w: 43, h: 53, anchor: { x: 21, y: 52 } },
  "heads/wagner-cripto": { w: 52, h: 56, anchor: { x: 26, y: 55 } },
  "icons/coin": { w: 21, h: 22 },
  "icons/diploma": { w: 22, h: 14 },
  "sceneries/academia": { w: 480, h: 270 },
  "sceneries/arena": { w: 480, h: 270 },
  "sceneries/casa-automatica": { w: 480, h: 270 },
  "sceneries/cidade": { w: 480, h: 270 },
  "sceneries/coordenacao": { w: 480, h: 270 },
  "sceneries/datacenter": { w: 480, h: 270 },
  "sceneries/deserto": { w: 480, h: 270 },
  "sceneries/formatura": { w: 480, h: 270 },
  "sceneries/laboratorio": { w: 480, h: 270 },
  "sceneries/nether": { w: 480, h: 270 },
  "sceneries/praia": { w: 480, h: 270 },
  "sceneries/prisao": { w: 480, h: 270 },
  "sceneries/sala-de-aula": { w: 480, h: 270 },
  "sceneries/templo": { w: 480, h: 270 },
  "skins/angelo-default": { w: 41, h: 48, anchor: { x: 20, y: 2 } },
  "skins/angelo-maestro": { w: 45, h: 48, anchor: { x: 18, y: 5 } },
  "skins/angelo-paraninfo": { w: 38, h: 48, anchor: { x: 19, y: 2 } },
  "skins/angelo-rei": { w: 39, h: 48, anchor: { x: 19, y: 2 } },
  "skins/angelo-terno": { w: 43, h: 48, anchor: { x: 19, y: 2 } },
  "skins/b1-default": { w: 43, h: 49, anchor: { x: 21, y: 2 } },
  "skins/b1-flexbox": { w: 35, h: 48, anchor: { x: 17, y: 2 } },
  "skins/b1-lancamento": { w: 39, h: 48, anchor: { x: 21, y: 2 } },
  "skins/b1-po": { w: 36, h: 48, anchor: { x: 17, y: 2 } },
  "skins/b1-rainha": { w: 48, h: 50, anchor: { x: 25, y: 6 } },
  "skins/b2-darkmode": { w: 33, h: 48, anchor: { x: 17, y: 2 } },
  "skins/b2-default": { w: 35, h: 48, anchor: { x: 18, y: 1 } },
  "skins/b2-paleta": { w: 32, h: 48, anchor: { x: 15, y: 7 } },
  "skins/b2-postit": { w: 41, h: 48, anchor: { x: 21, y: 2 } },
  "skins/b2-wireframe": { w: 41, h: 50, anchor: { x: 20, y: 2 } },
  "skins/edecio-atleta": { w: 41, h: 48, anchor: { x: 23, y: 2 } },
  "skins/edecio-cafe": { w: 34, h: 48, anchor: { x: 19, y: 2 } },
  "skins/edecio-ceo": { w: 41, h: 44, anchor: { x: 22, y: 2 } },
  "skins/edecio-chad": { w: 40, h: 48, anchor: { x: 22, y: 2 } },
  "skins/edecio-cria": { w: 32, h: 48, anchor: { x: 15, y: 2 } },
  "skins/edecio-default": { w: 38, h: 52, anchor: { x: 19, y: 1 } },
  "skins/edecio-full-dima": { w: 51, h: 48, anchor: { x: 31, y: 2 } },
  "skins/edecio-gladiador": { w: 40, h: 48, anchor: { x: 22, y: 2 } },
  "skins/edecio-prisioneiro": { w: 43, h: 47, anchor: { x: 24, y: 2 } },
  "skins/edecio-programador": { w: 37, h: 48, anchor: { x: 19, y: 2 } },
  "skins/edecio-samurai": { w: 34, h: 43, anchor: { x: 20, y: 5 } },
  "skins/gladimir-dba": { w: 40, h: 48, anchor: { x: 19, y: 2 } },
  "skins/gladimir-default": { w: 35, h: 48, anchor: { x: 18, y: 1 } },
  "skins/gladimir-maker": { w: 42, h: 48, anchor: { x: 18, y: 2 } },
  "skins/gladimir-mestre": { w: 43, h: 54, anchor: { x: 24, y: 9 } },
  "skins/gladimir-piloto": { w: 39, h: 48, anchor: { x: 19, y: 2 } },
  "skins/guto-astronauta": { w: 37, h: 48, anchor: { x: 18, y: 2 } },
  "skins/guto-churrasqueiro": { w: 36, h: 44, anchor: { x: 19, y: 3 } },
  "skins/guto-default": { w: 42, h: 48, anchor: { x: 20, y: 2 } },
  "skins/guto-dj": { w: 34, h: 48, anchor: { x: 17, y: 2 } },
  "skins/guto-pagodeiro": { w: 43, h: 48, anchor: { x: 19, y: 2 } },
  "skins/pablo-cientista": { w: 37, h: 48, anchor: { x: 18, y: 2 } },
  "skins/pablo-default": { w: 41, h: 47, anchor: { x: 20, y: 2 } },
  "skins/pablo-enxadrista": { w: 36, h: 48, anchor: { x: 18, y: 2 } },
  "skins/pablo-galactico": { w: 45, h: 48, anchor: { x: 21, y: 7 } },
  "skins/pablo-mago": { w: 46, h: 58, anchor: { x: 28, y: 16 } },
  "skins/wagner-agente": { w: 30, h: 48, anchor: { x: 14, y: 2 } },
  "skins/wagner-cripto": { w: 38, h: 42, anchor: { x: 17, y: 2 } },
  "skins/wagner-default": { w: 38, h: 52, anchor: { x: 19, y: 1 } },
  "skins/wagner-firewall": { w: 37, h: 42, anchor: { x: 18, y: 2 } },
  "skins/wagner-hacker": { w: 34, h: 48, anchor: { x: 17, y: 2 } },
};
