import type { ClickUpgradeDef } from './types';

/** 6 click upgrades spread over the cast. They share the `levels` map with disciplines, so ids must not collide. */
export const clickUpgrades: ClickUpgradeDef[] = [
  {
    id: 'muito-legal',
    professor: 'edecio',
    name: 'Muito Legal',
    emoji: '👍',
    description: 'Cada nível soma Edécoins ao valor de cada clique. O joinha do Edécio vale ouro.',
    baseCost: '60',
    baseClick: '0.1',
    requires: [],
  },
  {
    id: 'sensor-de-toque',
    professor: 'gladimir',
    name: 'Sensor de Toque',
    emoji: '📡',
    description: 'Cada nível soma Edécoins ao valor de cada clique. Detecta o dedo a três metros de distância.',
    baseCost: '2.5e4',
    baseClick: '3.6',
    requires: [{ kind: 'professorHired', professor: 'gladimir' }],
  },
  {
    id: 'botao-chamativo',
    professor: 'b2',
    name: 'Botão Chamativo',
    emoji: '🔘',
    description: 'Cada nível soma Edécoins ao valor de cada clique. Um botão tão bem desenhado que dá vontade de clicar.',
    baseCost: '2e7',
    baseClick: '1.7e3',
    requires: [{ kind: 'professorHired', professor: 'b2' }],
  },
  {
    id: 'clique-escalavel',
    professor: 'guto',
    name: 'Clique Escalável',
    emoji: '🖱️',
    description: 'Cada nível soma Edécoins ao valor de cada clique. O mesmo clique, rodando em mil servidores.',
    baseCost: '1e13',
    baseClick: '3.5e8',
    requires: [{ kind: 'professorHired', professor: 'guto' }],
  },
  {
    id: 'assinatura-do-coordenador',
    professor: 'angelo',
    name: 'Assinatura do Coordenador',
    emoji: '✍️',
    description: 'Cada nível soma Edécoins ao valor de cada clique. Um clique com firma reconhecida.',
    baseCost: '5e18',
    baseClick: '7.2e13',
    requires: [{ kind: 'professorHired', professor: 'angelo' }],
  },
  {
    id: 'clique-constante',
    professor: 'pablo',
    name: 'Clique O(1)',
    emoji: '⚡',
    description: 'Cada nível soma Edécoins ao valor de cada clique. Resposta em tempo constante, como manda o bom algoritmo.',
    baseCost: '4e21',
    baseClick: '4.4e15',
    requires: [{ kind: 'professorHired', professor: 'pablo' }],
  },
];
