import type { DisciplineDef } from './types';

/**
 * 24 disciplines, 3 per professor, in global order (hire order x tier).
 * Base cost grows about x9 per global tier starting at 15; base production about x6.5 starting at 0.2/s.
 * Tier 0 opens when the professor is hired; tier n opens when tier n-1 reaches level 10.
 */
export const disciplines: DisciplineDef[] = [
  // Edécio: API e Lógica de Programação
  {
    id: 'cafe-quentinho',
    professor: 'edecio',
    tier: 0,
    name: 'Café Quentinho',
    emoji: '☕',
    description: 'A aula de lógica começa com café. Gera Edécoins por segundo.',
    baseCost: '15',
    baseProduction: '0.2',
  },
  {
    id: 'programacao',
    professor: 'edecio',
    tier: 1,
    name: 'Programação',
    emoji: '💻',
    description: 'Variável, if, for e muita paciência. Gera Edécoins por segundo.',
    baseCost: '140',
    baseProduction: '1.5',
  },
  {
    id: 'projetinho',
    professor: 'edecio',
    tier: 2,
    name: 'Projetinho',
    emoji: '🗿',
    description: 'O trabalho que "é bem simples, dá pra fazer no fim de semana". Gera Edécoins por segundo.',
    baseCost: '1200',
    baseProduction: '12',
  },

  // Gladimir: Banco de Dados e IoT
  {
    id: 'select-sem-where',
    professor: 'gladimir',
    tier: 0,
    name: 'SELECT sem WHERE',
    emoji: '🗃️',
    description: 'Traz a galáxia inteira de dados de uma vez. Gera Edécoins por segundo.',
    baseCost: '11000',
    baseProduction: '91',
  },
  {
    id: 'join-galactico',
    professor: 'gladimir',
    tier: 1,
    name: 'JOIN Galáctico',
    emoji: '🪐',
    description: 'Une tabelas de planetas distantes. Que o JOIN esteja com você. Gera Edécoins por segundo.',
    baseCost: '98000',
    baseProduction: '700',
  },
  {
    id: 'estacao-iot',
    professor: 'gladimir',
    tier: 2,
    name: 'Estação Espacial IoT',
    emoji: '🛰️',
    description: 'Sensores em órbita mandando temperatura, umidade e curiosidades. Gera Edécoins por segundo.',
    baseCost: '890000',
    baseProduction: '5400',
  },

  // Bruna B2: Design UX
  {
    id: 'rascunho-de-persona',
    professor: 'b2',
    tier: 0,
    name: 'Rascunho de Persona',
    emoji: '👤',
    description: 'Dona Marlene, 52 anos, odeia pop-ups. Gera Edécoins por segundo.',
    baseCost: '8e6',
    baseProduction: '4.2e4',
  },
  {
    id: 'jornada-do-usuario',
    professor: 'b2',
    tier: 1,
    name: 'Jornada do Usuário',
    emoji: '🗺️',
    description: 'Mapa de tudo o que o usuário sente do clique ao checkout. Gera Edécoins por segundo.',
    baseCost: '7.2e7',
    baseProduction: '3.2e5',
  },
  {
    id: 'teste-com-usuario',
    professor: 'b2',
    tier: 2,
    name: 'Teste com Usuário Real',
    emoji: '🧪',
    description: 'Ninguém clica onde você imaginou. Gera Edécoins por segundo.',
    baseCost: '6.5e8',
    baseProduction: '2.5e6',
  },

  // Wagner: Cibersegurança e Redes
  {
    id: 'cabo-solto',
    professor: 'wagner',
    tier: 0,
    name: 'Cabo de Rede Solto',
    emoji: '🔌',
    description: 'Metade dos problemas de rede é um plugue mal encaixado. Gera Edécoins por segundo.',
    baseCost: '5.8e9',
    baseProduction: '1.9e7',
  },
  {
    id: 'firewall-de-papelao',
    professor: 'wagner',
    tier: 1,
    name: 'Firewall de Papelão',
    emoji: '🧱',
    description: 'Protege até chegar a primeira chuva de pacotes. Gera Edécoins por segundo.',
    baseCost: '5.2e10',
    baseProduction: '1.5e8',
  },
  {
    id: 'pentest-amistoso',
    professor: 'wagner',
    tier: 2,
    name: 'Pentest Amistoso',
    emoji: '🕵️',
    description: 'Invadir o próprio sistema, com autorização e sorriso. Gera Edécoins por segundo.',
    baseCost: '4.7e11',
    baseProduction: '1.1e9',
  },

  // Guto: Arquitetura em Nuvem
  {
    id: 'deploy-na-sexta',
    professor: 'guto',
    tier: 0,
    name: 'Deploy na Sexta',
    emoji: '🚀',
    description: 'O que pode dar errado? (o fim de semana inteiro). Gera Edécoins por segundo.',
    baseCost: '4.2e12',
    baseProduction: '8.7e9',
  },
  {
    id: 'conteiner-sem-medo',
    professor: 'guto',
    tier: 1,
    name: 'Contêiner Sem Medo',
    emoji: '📦',
    description: 'Na minha máquina funcionava. Agora funciona na de todo mundo. Gera Edécoins por segundo.',
    baseCost: '3.8e13',
    baseProduction: '6.7e10',
  },
  {
    id: 'nuvem-multirregiao',
    professor: 'guto',
    tier: 2,
    name: 'Nuvem Multirregião',
    emoji: '🌍',
    description: 'Seu servidor em três continentes e a conta em todos eles. Gera Edécoins por segundo.',
    baseCost: '3.4e14',
    baseProduction: '5.2e11',
  },

  // Bruna B1: Produtos e CSS/UX
  {
    id: 'padding-ou-margin',
    professor: 'b1',
    tier: 0,
    name: 'Padding ou Margin?',
    emoji: '📏',
    description: 'A dúvida eterna do espaçamento. Gera Edécoins por segundo.',
    baseCost: '3.1e15',
    baseProduction: '4e12',
  },
  {
    id: 'pixel-fora-do-lugar',
    professor: 'b1',
    tier: 1,
    name: 'Pixel Fora do Lugar',
    emoji: '🔍',
    description: 'Só ela vê, e depois de ver ninguém consegue mais ignorar. Gera Edécoins por segundo.',
    baseCost: '2.8e16',
    baseProduction: '3.1e13',
  },
  {
    id: 'backlog-infinito',
    professor: 'b1',
    tier: 2,
    name: 'Backlog Infinito',
    emoji: '📋',
    description: 'Cada card entregue gera dois novos. Gera Edécoins por segundo.',
    baseCost: '2.5e17',
    baseProduction: '2.4e14',
  },

  // Angelo: Coordenação e POO
  {
    id: 'ata-de-reuniao',
    professor: 'angelo',
    tier: 0,
    name: 'Ata de Reunião',
    emoji: '📜',
    description: 'Tudo o que foi decidido, e o que ficou para a próxima. Gera Edécoins por segundo.',
    baseCost: '2.3e18',
    baseProduction: '1.8e15',
  },
  {
    id: 'heranca-multipla',
    professor: 'angelo',
    tier: 1,
    name: 'Herança Múltipla',
    emoji: '🧬',
    description: 'Uma classe filha com tantos pais que ninguém sabe de quem é o método. Gera Edécoins por segundo.',
    baseCost: '2e19',
    baseProduction: '1.4e16',
  },
  {
    id: 'polimorfismo',
    professor: 'angelo',
    tier: 2,
    name: 'Polimorfismo',
    emoji: '🎭',
    description: 'Mesmo método, vários comportamentos, uma só coordenação. Gera Edécoins por segundo.',
    baseCost: '1.8e20',
    baseProduction: '1.1e17',
  },

  // Pablo: Algoritmos e Estrutura de Dados
  {
    id: 'lista-encadeada',
    professor: 'pablo',
    tier: 0,
    name: 'Lista Encadeada',
    emoji: '🔗',
    description: 'Cada elo sabe quem vem depois. O resto, ele finge que sabe. Gera Edécoins por segundo.',
    baseCost: '1.6e21',
    baseProduction: '8.3e17',
  },
  {
    id: 'pilha-e-fila',
    professor: 'pablo',
    tier: 1,
    name: 'Pilha e Fila',
    emoji: '🥞',
    description: 'Quem chega por último sai primeiro, mas só na pilha. Gera Edécoins por segundo.',
    baseCost: '1.5e22',
    baseProduction: '6.4e18',
  },
  {
    id: 'grafo-caminho-minimo',
    professor: 'pablo',
    tier: 2,
    name: 'Grafo e Caminho Mínimo',
    emoji: '🕸️',
    description: 'O menor caminho entre dois pontos. Pablo já sabia a resposta. Gera Edécoins por segundo.',
    baseCost: '1.3e23',
    baseProduction: '4.9e19',
  },
];
