import type { PrestigeNodeDef } from './types';

/**
 * Permanent tree bought with diplomas. Layout (col, row), root at row 0:
 *
 *   col 0-1: click   col 2-4: core (trunk in col 3)   col 5: idle   col 6: events
 *
 * Costs are in diplomas; `costGrowth` is an integer so every level costs a whole number.
 * Effects apply once per level owned. The diploma scale will be retuned with the simulator.
 */
export const prestigeNodes: PrestigeNodeDef[] = [
  // ------------------------------------------------------------------ core (trunk)
  {
    id: 'core-diploma',
    branch: 'core',
    name: 'Diploma na Parede',
    emoji: '🎓',
    description: 'Cada nível multiplica toda a produção e todo clique por 1,1. Fica bonito na parede e na planilha.',
    cost: 5,
    costGrowth: 2,
    maxLevel: 6,
    effects: [{ stat: 'globalPower', op: 'mult', value: 1.1 }],
    requires: [],
    position: { col: 3, row: 0 },
  },
  {
    id: 'core-keep-gladimir',
    branch: 'core',
    name: 'Gladimir Fica',
    emoji: '🚀',
    description: 'O Gladimir continua contratado depois de cada Formatura. A Força dele não passa pela secretaria.',
    cost: 10,
    costGrowth: 1,
    maxLevel: 1,
    effects: [],
    requires: ['core-diploma'],
    position: { col: 3, row: 1 },
    keepsProfessors: ['gladimir'],
  },
  {
    id: 'core-keep-b2',
    branch: 'core',
    name: 'Bruna B2 Fica',
    emoji: '🎨',
    description: 'A Bruna B2 continua contratada depois de cada Formatura. Interface boa a gente não joga fora.',
    cost: 25,
    costGrowth: 1,
    maxLevel: 1,
    effects: [],
    requires: ['core-keep-gladimir'],
    position: { col: 3, row: 2 },
    keepsProfessors: ['b2'],
  },
  {
    id: 'core-keep-wagner',
    branch: 'core',
    name: 'Wagner Fica',
    emoji: '🛡️',
    description: 'O Wagner continua contratado depois de cada Formatura. Alguém precisa vigiar a rede nas férias.',
    cost: 60,
    costGrowth: 1,
    maxLevel: 1,
    effects: [],
    requires: ['core-keep-b2'],
    position: { col: 3, row: 3 },
    keepsProfessors: ['wagner'],
  },
  {
    id: 'core-keep-guto',
    branch: 'core',
    name: 'Guto Fica',
    emoji: '☁️',
    description: 'O Guto continua contratado depois de cada Formatura. A festa de recomeço já está marcada.',
    cost: 150,
    costGrowth: 1,
    maxLevel: 1,
    effects: [],
    requires: ['core-keep-wagner'],
    position: { col: 3, row: 4 },
    keepsProfessors: ['guto'],
  },
  {
    id: 'core-nota-maxima',
    branch: 'core',
    name: 'Nota Máxima',
    emoji: '📈',
    description: 'Cada nível multiplica por 1,1 os diplomas ganhos em cada Formatura. Dez no boletim, mais dez no diploma.',
    cost: 15,
    costGrowth: 2,
    maxLevel: 5,
    effects: [{ stat: 'diplomaGain', op: 'mult', value: 1.1 }],
    requires: ['core-keep-gladimir'],
    position: { col: 2, row: 2 },
  },
  {
    id: 'core-formatura-de-honra',
    branch: 'core',
    name: 'Formatura de Honra',
    emoji: '🏅',
    description: 'Cada nível multiplica por 1,25 os diplomas ganhos. Menção honrosa e um canudo maior.',
    cost: 100,
    costGrowth: 3,
    maxLevel: 3,
    effects: [{ stat: 'diplomaGain', op: 'mult', value: 1.25 }],
    requires: ['core-nota-maxima'],
    position: { col: 2, row: 3 },
  },
  {
    id: 'core-trabalho-em-equipe',
    branch: 'core',
    name: 'Trabalho em Equipe',
    emoji: '🤝',
    description: 'Cada nível soma 1 ponto percentual de sinergia por professor contratado. Grupo bom divide a nota e a tarefa.',
    cost: 20,
    costGrowth: 2,
    maxLevel: 5,
    effects: [{ stat: 'synergy', op: 'add', value: 0.01 }],
    requires: ['core-keep-b2'],
    position: { col: 4, row: 3 },
  },

  // ------------------------------------------------------------------ click
  {
    id: 'click-dedo-treinado',
    branch: 'click',
    name: 'Dedo Treinado',
    emoji: '👆',
    description: 'Cada nível multiplica o valor do clique por 1,5. Músculo de clique também cresce com a prática.',
    cost: 3,
    costGrowth: 2,
    maxLevel: 6,
    effects: [{ stat: 'clickPower', op: 'mult', value: 1.5 }],
    requires: ['core-diploma'],
    position: { col: 1, row: 1 },
  },
  {
    id: 'click-olho-clinico',
    branch: 'click',
    name: 'Olho Clínico',
    emoji: '🎯',
    description: 'Cada nível soma 2 pontos percentuais à chance de crítico. Quem viu o bug, viu.',
    cost: 8,
    costGrowth: 2,
    maxLevel: 5,
    effects: [{ stat: 'critChance', op: 'add', value: 0.02 }],
    requires: ['click-dedo-treinado'],
    position: { col: 0, row: 2 },
  },
  {
    id: 'click-joinha-dobrado',
    branch: 'click',
    name: 'Joinha Dobrado',
    emoji: '👍',
    description: 'Cada nível multiplica o multiplicador do crítico por 1,2. Muito legal, e ainda mais um pouco.',
    cost: 12,
    costGrowth: 2,
    maxLevel: 5,
    effects: [{ stat: 'critMult', op: 'mult', value: 1.2 }],
    requires: ['click-dedo-treinado'],
    position: { col: 1, row: 2 },
  },
  {
    id: 'click-combo-eterno',
    branch: 'click',
    name: 'Combo Eterno',
    emoji: '🔥',
    description: 'Cada nível soma 5 passos ao combo máximo. Quem não solta o mouse não perde o ritmo.',
    cost: 20,
    costGrowth: 2,
    maxLevel: 4,
    effects: [{ stat: 'comboMax', op: 'add', value: 5 }],
    requires: ['click-olho-clinico'],
    position: { col: 0, row: 3 },
  },
  {
    id: 'click-clique-sabio',
    branch: 'click',
    name: 'Clique Sábio',
    emoji: '🧠',
    description: 'Cada nível soma ao clique 1% da sua produção por segundo. O clique aprende com a turma.',
    cost: 40,
    costGrowth: 2,
    maxLevel: 5,
    effects: [{ stat: 'clickFromIdle', op: 'add', value: 0.01 }],
    requires: ['click-joinha-dobrado'],
    position: { col: 1, row: 3 },
  },

  // ------------------------------------------------------------------ idle
  {
    id: 'idle-hora-extra',
    branch: 'idle',
    name: 'Hora Extra',
    emoji: '⏰',
    description: 'Cada nível multiplica a produção de todas as disciplinas por 1,25. Ninguém pediu, todo mundo agradece.',
    cost: 3,
    costGrowth: 2,
    maxLevel: 6,
    effects: [{ stat: 'idlePower', op: 'mult', value: 1.25 }],
    requires: ['core-diploma'],
    position: { col: 5, row: 1 },
  },
  {
    id: 'idle-dormir-em-paz',
    branch: 'idle',
    name: 'Dormir em Paz',
    emoji: '😴',
    description: 'Cada nível soma 2 horas ao limite do ganho offline. O servidor trabalha, você descansa.',
    cost: 10,
    costGrowth: 2,
    maxLevel: 4,
    effects: [{ stat: 'offlineHours', op: 'add', value: 2 }],
    requires: ['idle-hora-extra'],
    position: { col: 5, row: 2 },
  },
  {
    id: 'idle-sensores-eternos',
    branch: 'idle',
    name: 'Sensores Eternos',
    emoji: '📡',
    description: 'Cada nível soma 1 clique automático por segundo. A bateria é da turma anterior.',
    cost: 15,
    costGrowth: 2,
    maxLevel: 5,
    effects: [{ stat: 'autoClicks', op: 'add', value: 1 }],
    requires: ['idle-dormir-em-paz'],
    position: { col: 5, row: 3 },
  },
  {
    id: 'idle-mensalidade-menor',
    branch: 'idle',
    name: 'Mensalidade Menor',
    emoji: '🏷️',
    description: 'Cada nível multiplica por 0,95 o custo de disciplinas e upgrades de clique. Bolsa de estudos para o Edécoin.',
    cost: 40,
    costGrowth: 2,
    maxLevel: 5,
    effects: [{ stat: 'costMult', op: 'mult', value: 0.95 }],
    requires: ['idle-sensores-eternos'],
    position: { col: 5, row: 4 },
  },

  // ------------------------------------------------------------------ events
  {
    id: 'events-radar-ligado',
    branch: 'events',
    name: 'Radar Ligado',
    emoji: '📶',
    description: 'Cada nível multiplica por 0,9 o tempo entre invasões. Mais alerta, mais recompensa.',
    cost: 3,
    costGrowth: 2,
    maxLevel: 5,
    effects: [{ stat: 'eventInterval', op: 'mult', value: 0.9 }],
    requires: ['core-diploma'],
    position: { col: 6, row: 1 },
  },
  {
    id: 'events-bug-bounty',
    branch: 'events',
    name: 'Bug Bounty',
    emoji: '💰',
    description: 'Cada nível multiplica por 1,2 a recompensa das invasões defendidas. Achar a falha também paga.',
    cost: 10,
    costGrowth: 2,
    maxLevel: 5,
    effects: [{ stat: 'eventReward', op: 'mult', value: 1.2 }],
    requires: ['events-radar-ligado'],
    position: { col: 6, row: 2 },
  },
  {
    id: 'events-reflexo-rapido',
    branch: 'events',
    name: 'Reflexo Rápido',
    emoji: '⏳',
    description: 'Cada nível multiplica por 1,1 o tempo que uma invasão fica na tela. Mais tempo para clicar com calma.',
    cost: 15,
    costGrowth: 2,
    maxLevel: 5,
    effects: [{ stat: 'eventWindow', op: 'mult', value: 1.1 }],
    requires: ['events-bug-bounty'],
    position: { col: 6, row: 3 },
  },
  {
    id: 'events-sprints-generosos',
    branch: 'events',
    name: 'Sprints Generosos',
    emoji: '🏁',
    description: 'Cada nível multiplica por 1,2 a recompensa dos sprints. O backlog também vira mais bonzinho.',
    cost: 30,
    costGrowth: 2,
    maxLevel: 5,
    effects: [{ stat: 'sprintReward', op: 'mult', value: 1.2 }],
    requires: ['events-reflexo-rapido'],
    position: { col: 6, row: 4 },
  },
];
