import type { ProfessorDef, ProfessorId } from './types';

/**
 * The cast, in hire order. Each professor requires the previous one to be hired;
 * hire costs sit between the last discipline of the previous professor and the
 * first discipline of the new one (see disciplines.ts).
 */
export const professors: Record<ProfessorId, ProfessorDef> = {
  edecio: {
    id: 'edecio',
    name: 'Edécio',
    subject: 'API e Lógica de Programação',
    tagline: 'Clique com combo e crítico: quanto mais rápido você clica, mais legal fica.',
    color: '#e5484d',
    order: 1,
    hireCost: '0',
    requires: [],
    features: ['combo'],
    quotes: {
      hire: 'Muito legal! Seja bem-vindo à turma. 👍',
      click: ['Muito legal! 👍', 'Parabéns!', 'Isso! 👍', 'Tá certo. Muito legal.', 'Excelente, parabéns!'],
      idle: [
        'Pode continuar, está indo muito bem.',
        'Lógica é isso: um passo de cada vez, sorrindo.',
        'Quem programa com calma programa uma vez só. 👍',
      ],
      milestone: ['Parabéns! Mais um nível. 👍', 'Subiu de nível. Muito legal!', 'Olha só, parabéns!'],
    },
  },
  gladimir: {
    id: 'gladimir',
    name: 'Gladimir',
    subject: 'Banco de Dados e IoT',
    tagline: 'Produção parada também rende: ganho offline e cliques automáticos dos sensores.',
    color: '#3b82f6',
    order: 2,
    hireCost: '7840',
    requires: [{ kind: 'professorHired', professor: 'edecio' }],
    features: ['offline'],
    quotes: {
      hire: 'Que o JOIN esteja com você! Estou dentro.',
      click: [
        'SELECT * FROM sucesso;',
        'Boa, jovem cavaleiro espacial!',
        'Essa query tem a Força.',
        'Tabela bonita é tabela normalizada.',
      ],
      idle: [
        'Meus sensores dizem que a produção vai bem.',
        'Banco de dados é só uma galáxia muito organizada.',
        'Quem não faz backup sente um grande distúrbio na Força.',
        'Esse sabre de luz também roda em 3,3 volts.',
      ],
      milestone: ['O índice subiu: consulta ainda mais rápida!', 'Esse nível merece um COMMIT épico.'],
    },
  },
  b2: {
    id: 'b2',
    name: 'Bruna B2',
    subject: 'Design UX',
    tagline: 'Conforto: compra em lote, descontos e temas de cor para a interface.',
    color: '#ec4899',
    order: 3,
    hireCost: '9.64e5',
    requires: [{ kind: 'professorHired', professor: 'gladimir' }],
    features: ['bulkBuy', 'hudThemes'],
    quotes: {
      hire: 'Oi! Vou deixar tudo mais confortável por aqui.',
      click: ['Boa! Clique bem posicionado.', 'Botão grande, clique fácil.', 'Usabilidade aprovada.', 'Foi intuitivo, né?'],
      idle: [
        'Dica: contraste ajuda todo mundo.',
        'Se o usuário precisa de manual, o design pode melhorar.',
        'Testei com cinco pessoas: todas acharam o botão.',
      ],
      milestone: ['Nível novo, interface mais gostosa de usar!', 'Isso merece uma microinteração!'],
    },
  },
  wagner: {
    id: 'wagner',
    name: 'Wagner',
    subject: 'Cibersegurança e Redes',
    tagline: 'Invasões na tela: defenda o campus clicando nas ameaças a tempo.',
    color: '#22c55e',
    order: 4,
    hireCost: '1.3e9',
    requires: [{ kind: 'professorHired', professor: 'b2' }],
    features: ['events'],
    quotes: {
      hire: 'Cheguei. Primeira regra: ninguém usa 123456 de senha.',
      click: ['Acesso permitido.', 'Pacote entregue.', 'Sem alertas por enquanto.', 'Autenticado!'],
      idle: [
        'Monitorando a rede. Tudo calmo.',
        'Troque sua senha. Sim, você.',
        'Se o cabo está solto, o problema é físico (e curiosamente comum).',
      ],
      milestone: ['Patch aplicado, nível atualizado.', 'Mais um nível, zero vazamentos.'],
    },
  },
  guto: {
    id: 'guto',
    name: 'Guto',
    subject: 'Arquitetura em Nuvem',
    tagline: 'Escala: habilidades com recarga que turbinam a produção por alguns segundos.',
    color: '#06b6d4',
    order: 5,
    hireCost: '9.66e11',
    requires: [{ kind: 'professorHired', professor: 'wagner' }],
    features: ['abilities'],
    quotes: {
      hire: 'Bora! A nuvem e a resenha eu resolvo.',
      click: ['Bora! 🎉', 'Show de bola!', 'Subiu pra produção, tamo junto!', 'Boa vibe, boa nuvem.'],
      idle: [
        'Já tem churrasco marcado depois do deploy?',
        'Só sobe pra produção se tiver pagode ao fundo.',
        'Escalou sozinho. Dá pra aproveitar a vibe.',
        'Deploy na sexta? Bora, depois a gente vê o que quebrou.',
      ],
      milestone: ['Escalou! Bora comemorar!', 'Nível novo, vibe nova!'],
    },
  },
  b1: {
    id: 'b1',
    name: 'Bruna B1',
    subject: 'Produtos e CSS/UX',
    tagline: 'Missões: sprints com meta, prazo e recompensa.',
    color: '#a855f7',
    order: 6,
    hireCost: '9.62e14',
    requires: [{ kind: 'professorHired', professor: 'guto' }],
    features: ['sprints'],
    quotes: {
      hire: 'Oi, time! Vamos organizar esse backlog (ele é grande).',
      click: ['Entregue!', 'Mais um card movido para Done.', 'Alinhado com o produto.', 'Pixel no lugar, cliente feliz.'],
      idle: [
        'O backlog agradece a visita. Ele nunca esvazia.',
        'Padding ou margin? Hoje eu vou de gap.',
        'Um pixel fora do lugar não me deixa dormir (só um pixel).',
      ],
      milestone: ['Sprint fechada!', 'Mais um incremento entregue.'],
    },
  },
  angelo: {
    id: 'angelo',
    name: 'Angelo',
    subject: 'Coordenação e POO',
    tagline: 'Sinergia entre professores e a Formatura, o prestígio do curso.',
    color: '#f59e0b',
    order: 7,
    hireCost: '5.42e17',
    requires: [{ kind: 'professorHired', professor: 'b1' }],
    features: ['synergy', 'graduation'],
    quotes: {
      hire: 'Senhores, com licença: a coordenação está presente. Bom trabalho a todos.',
      click: [
        'Assunto encerrado. Próximo item da pauta.',
        'Aprovado em ata.',
        'Registre-se: foi um bom clique.',
        'Cumpra-se.',
      ],
      idle: [
        'Esta reunião poderia ter sido um e-mail. Este aviso é o e-mail.',
        'Pauta do dia: tudo.',
        'Lembrando: o prazo é sagrado. Sagrado, no caso, é uma palavra flexível.',
      ],
      milestone: ['Registre-se em ata: novo nível alcançado.', 'Excelência acadêmica, senhores.'],
    },
  },
  pablo: {
    id: 'pablo',
    name: 'Pablo',
    subject: 'Algoritmos e Estrutura de Dados',
    tagline: 'Otimização: pesquisas que deixam todo o resto mais barato. Exige uma formatura.',
    color: '#6366f1',
    order: 8,
    hireCost: '8e20',
    requires: [
      { kind: 'professorHired', professor: 'angelo' },
      { kind: 'graduations', count: 1 },
    ],
    features: ['complexity'],
    quotes: {
      hire: 'Bora otimizar isso juntos? Algoritmo bom é o que a turma inteira entende.',
      click: ['Boa! Isso roda em O(1).', 'Clique limpo, sem efeito colateral.', 'Compilou de primeira.', 'Esse clique merecia um commit.'],
      idle: [
        'Rede neural também aprende errando. Segue o treino.',
        'Todo problema grande é um monte de problema pequeno bem dividido.',
        'A IA até escreve o código, mas quem entende o algoritmo sabe o que pedir.',
        'Estrutura de dados certa é metade da solução.',
      ],
      milestone: ['Convergiu! Mais um nível.', 'Otimização encontrada. A turma está voando.'],
    },
  },
};
