import type { Requirement, ResearchDef } from './types';

const level = (discipline: string, minLevel: number): Requirement => ({
  kind: 'disciplineLevel',
  discipline,
  level: minLevel,
});

/**
 * One-time purchases, 4 to 6 per professor. This is where each professor's layer gets better.
 * Costs sit near the price of the professor's own disciplines at the moment the research unlocks.
 */
export const research: ResearchDef[] = [
  // ---------------------------------------------------------------- Edécio: combo and crit
  {
    id: 'edecio-academia',
    professor: 'edecio',
    name: 'Academia Avenida',
    emoji: '💪',
    description: 'Cada passo do combo vale mais: +0,02 de bônus por passo. Treino de braço rende clique forte.',
    cost: '400',
    effects: [{ stat: 'comboStep', op: 'add', value: 0.02 }],
    requires: [level('cafe-quentinho', 10)],
  },
  {
    id: 'edecio-atleta',
    professor: 'edecio',
    name: 'Atleta',
    emoji: '⚽️',
    description: 'O combo pode chegar a +10 passos a mais. Fôlego de quem joga bola toda semana.',
    cost: '2500',
    effects: [{ stat: 'comboMax', op: 'add', value: 10 }],
    requires: [level('programacao', 5)],
  },
  {
    id: 'edecio-cria',
    professor: 'edecio',
    name: 'Cria',
    emoji: '🤬',
    description: 'Aumenta em 3 pontos percentuais a chance de crítico. Quando dá certo, ele só sorri.',
    cost: '15000',
    effects: [{ stat: 'critChance', op: 'add', value: 0.03 }],
    requires: [level('programacao', 15)],
  },
  {
    id: 'edecio-full-dima',
    professor: 'edecio',
    name: 'Full Dima',
    emoji: '💎',
    description: 'O multiplicador do crítico fica 50% maior. Cada joinha vem com armadura de diamante.',
    cost: '60000',
    effects: [{ stat: 'critMult', op: 'mult', value: 1.5 }],
    requires: [level('projetinho', 5)],
  },
  {
    id: 'edecio-samurai',
    professor: 'edecio',
    name: 'Samurai',
    emoji: '🥷🏻',
    description: 'O valor de todo clique dobra. Um corte só, limpo e sorridente.',
    cost: '600000',
    effects: [{ stat: 'clickPower', op: 'mult', value: 2 }],
    requires: [level('projetinho', 25)],
  },
  {
    id: 'edecio-aula-show',
    professor: 'edecio',
    name: 'Aula Show',
    emoji: '🎤',
    description: 'Libera a habilidade Aula Show (clique x10 por 15 s). Precisa do Guto contratado. Muito legal!',
    cost: '3e12',
    effects: [],
    requires: [{ kind: 'professorHired', professor: 'guto' }],
    unlocksAbility: 'aula-show',
  },

  // ---------------------------------------------------------------- Gladimir: idle and offline
  {
    id: 'gladimir-backup',
    professor: 'gladimir',
    name: 'Backup Noturno',
    emoji: '🌙',
    description: 'O banco guarda +4 horas de ganho offline. Dados salvos, café esfriando.',
    cost: '40000',
    effects: [{ stat: 'offlineHours', op: 'add', value: 4 }],
    requires: [level('select-sem-where', 5)],
  },
  {
    id: 'gladimir-casa-automatica',
    professor: 'gladimir',
    name: 'Casa Automática',
    emoji: '🏠',
    description: 'Sensores IoT dão +1 clique automático por segundo. A luz acende sozinha, o clique também.',
    cost: '150000',
    effects: [{ stat: 'autoClicks', op: 'add', value: 1 }],
    requires: [level('select-sem-where', 10)],
  },
  {
    id: 'gladimir-replica',
    professor: 'gladimir',
    name: 'Réplica Intergaláctica',
    emoji: '🌌',
    description: 'Ganha +25 pontos percentuais da produção enquanto você está fora. Cópia do banco em outra galáxia.',
    cost: '1e6',
    effects: [{ stat: 'offlineRate', op: 'add', value: 0.25 }],
    requires: [level('join-galactico', 5)],
  },
  {
    id: 'gladimir-sensores',
    professor: 'gladimir',
    name: 'Sensores em Rede',
    emoji: '📶',
    description: 'Mais +3 cliques automáticos por segundo. Um sensor avisa o outro, e todos clicam.',
    cost: '4e6',
    effects: [{ stat: 'autoClicks', op: 'add', value: 3 }],
    requires: [level('estacao-iot', 5)],
  },
  {
    id: 'gladimir-forca-do-cache',
    professor: 'gladimir',
    name: 'A Força do Cache',
    emoji: '✨',
    description:
      'Banco offline chega a +6 horas e mais +25 pontos de taxa (com os outros, 12 h a 100%). Disciplinas do Gladimir x2. A Força está com o cache.',
    cost: '5e7',
    effects: [
      { stat: 'offlineHours', op: 'add', value: 6 },
      { stat: 'offlineRate', op: 'add', value: 0.25 },
      { stat: 'prof:gladimir', op: 'mult', value: 2 },
    ],
    requires: [level('estacao-iot', 15)],
  },
  {
    id: 'gladimir-hiperespaco',
    professor: 'gladimir',
    name: 'Salto no Hiperespaço',
    emoji: '🚀',
    description: 'Libera a habilidade Salto no Hiperespaço (+20 cliques automáticos por segundo por 20 s). Precisa do Guto contratado.',
    cost: '6e12',
    effects: [],
    requires: [{ kind: 'professorHired', professor: 'guto' }],
    unlocksAbility: 'hiperespaco',
  },

  // ---------------------------------------------------------------- Bruna B2: comfort
  {
    id: 'b2-prototipo-de-papel',
    professor: 'b2',
    name: 'Protótipo de Papel',
    emoji: '📝',
    description: 'Disciplinas e upgrades de clique custam 5% menos. Errar no papel sai mais barato.',
    cost: '3e7',
    effects: [{ stat: 'costMult', op: 'mult', value: 0.95 }],
    requires: [level('rascunho-de-persona', 5)],
  },
  {
    id: 'b2-heuristicas',
    professor: 'b2',
    name: 'Heurísticas de Nielsen',
    emoji: '🧭',
    description: 'Mais 5% de desconto em disciplinas e upgrades de clique. Dez regras, nenhuma delas é "faça maior".',
    cost: '3e8',
    effects: [{ stat: 'costMult', op: 'mult', value: 0.95 }],
    requires: [level('jornada-do-usuario', 5)],
  },
  {
    id: 'b2-microinteracoes',
    professor: 'b2',
    name: 'Microinterações',
    emoji: '✨',
    description: 'Invasões ficam 25% mais tempo na tela e buffs de habilidades duram 25% mais. Um brilhinho no lugar certo.',
    cost: '4e9',
    effects: [
      { stat: 'eventWindow', op: 'mult', value: 1.25 },
      { stat: 'abilityDuration', op: 'mult', value: 1.25 },
    ],
    requires: [level('teste-com-usuario', 5)],
  },
  {
    id: 'b2-pesquisa-de-satisfacao',
    professor: 'b2',
    name: 'Pesquisa de Satisfação',
    emoji: '📋',
    description: 'Mais 10% de desconto em disciplinas e upgrades de clique. Nota 10 em usabilidade, nota 9 em paciência.',
    cost: '4e10',
    effects: [{ stat: 'costMult', op: 'mult', value: 0.9 }],
    requires: [level('teste-com-usuario', 15)],
  },
  {
    id: 'b2-design-system',
    professor: 'b2',
    name: 'Design System',
    emoji: '🎨',
    description: 'Disciplinas da B2 x2 e mais 5% de desconto. Todos os botões finalmente parecem irmãos.',
    cost: '2e11',
    effects: [
      { stat: 'prof:b2', op: 'mult', value: 2 },
      { stat: 'costMult', op: 'mult', value: 0.95 },
    ],
    requires: [level('teste-com-usuario', 25)],
  },

  // ---------------------------------------------------------------- Wagner: invasions
  {
    id: 'wagner-radar',
    professor: 'wagner',
    name: 'Radar de Ameaças',
    emoji: '📡',
    description: 'Invasões aparecem com 15% mais frequência. Ver o problema cedo é metade da solução.',
    cost: '3e10',
    effects: [{ stat: 'eventInterval', op: 'mult', value: 0.85 }],
    requires: [level('cabo-solto', 5)],
  },
  {
    id: 'wagner-senha-forte',
    professor: 'wagner',
    name: 'Senha Forte',
    emoji: '🔐',
    description: 'Recompensa das invasões defendidas 50% maior. Letra, número, símbolo e nenhum 123456.',
    cost: '3.5e11',
    effects: [{ stat: 'eventReward', op: 'mult', value: 1.5 }],
    requires: [level('firewall-de-papelao', 5)],
  },
  {
    id: 'wagner-prisao',
    professor: 'wagner',
    name: 'Prisão',
    emoji: '⛓️',
    description: 'Invasões ficam 25% mais tempo na tela antes de escapar. A ameaça fica presa para você ter tempo de clicar.',
    cost: '3e12',
    effects: [{ stat: 'eventWindow', op: 'mult', value: 1.25 }],
    requires: [level('pentest-amistoso', 5)],
  },
  {
    id: 'wagner-honeypot',
    professor: 'wagner',
    name: 'Honeypot',
    emoji: '🍯',
    description: 'Invasões 15% mais frequentes e com 50% mais recompensa. Isca doce para atacante apressado.',
    cost: '2e13',
    effects: [
      { stat: 'eventInterval', op: 'mult', value: 0.85 },
      { stat: 'eventReward', op: 'mult', value: 1.5 },
    ],
    requires: [level('pentest-amistoso', 15)],
  },
  {
    id: 'wagner-gladiador',
    professor: 'wagner',
    name: 'Gladiador do Firewall',
    emoji: '🗡️',
    description: 'Disciplinas do Wagner x2 e mais 25% de recompensa nas invasões. Entra na arena e sai sem vazamento.',
    cost: '1.5e14',
    effects: [
      { stat: 'prof:wagner', op: 'mult', value: 2 },
      { stat: 'eventReward', op: 'mult', value: 1.25 },
    ],
    requires: [level('pentest-amistoso', 25)],
  },

  // ---------------------------------------------------------------- Guto: abilities
  {
    id: 'guto-escala-horizontal',
    professor: 'guto',
    name: 'Escala Horizontal',
    emoji: '↔️',
    description: 'Habilidades recarregam 15% mais rápido. Se não aguenta, põe mais máquinas (e mais gente na festa).',
    cost: '3e13',
    effects: [{ stat: 'abilityCooldown', op: 'mult', value: 0.85 }],
    requires: [level('deploy-na-sexta', 5)],
  },
  {
    id: 'guto-balanceador',
    professor: 'guto',
    name: 'Balanceador de Carga',
    emoji: '⚖️',
    description: 'Buffs das habilidades duram 25% mais. A carga fica bem distribuída, igual a fila do churrasco.',
    cost: '2.5e14',
    effects: [{ stat: 'abilityDuration', op: 'mult', value: 1.25 }],
    requires: [level('conteiner-sem-medo', 5)],
  },
  {
    id: 'guto-prainha',
    professor: 'guto',
    name: 'Prainha',
    emoji: '🏝️',
    description: 'Habilidades recarregam 20% mais rápido. O servidor se vira sozinho enquanto o time está na prainha.',
    cost: '2.5e15',
    effects: [{ stat: 'abilityCooldown', op: 'mult', value: 0.8 }],
    requires: [level('nuvem-multirregiao', 5)],
  },
  {
    id: 'guto-cidade-serverless',
    professor: 'guto',
    name: 'Cidade Serverless',
    emoji: '🏙️',
    description: 'Disciplinas do Guto x2 e buffs 20% mais longos. Uma cidade inteira sem servidor para cuidar (ele existe, só não é problema seu).',
    cost: '2e16',
    effects: [
      { stat: 'prof:guto', op: 'mult', value: 2 },
      { stat: 'abilityDuration', op: 'mult', value: 1.2 },
    ],
    requires: [level('nuvem-multirregiao', 15)],
  },

  // ---------------------------------------------------------------- Bruna B1: sprints
  {
    id: 'b1-nether-do-backlog',
    professor: 'b1',
    name: 'Nether do Backlog',
    emoji: '🕳️',
    description: 'Recompensa dos sprints 50% maior. Quanto mais fundo no backlog, mais item.',
    cost: '2e16',
    effects: [{ stat: 'sprintReward', op: 'mult', value: 1.5 }],
    requires: [level('padding-ou-margin', 5)],
  },
  {
    id: 'b1-flexbox',
    professor: 'b1',
    name: 'Flexbox',
    emoji: '📐',
    description: 'Disciplinas da Bruna B1 x2. Tudo alinhado, sem nenhum float para limpar.',
    cost: '1.8e17',
    effects: [{ stat: 'prof:b1', op: 'mult', value: 2 }],
    requires: [level('pixel-fora-do-lugar', 5)],
  },
  {
    id: 'b1-retrospectiva',
    professor: 'b1',
    name: 'Retrospectiva',
    emoji: '🔁',
    description: 'Recompensa dos sprints mais 50% maior. O que foi bem, o que foi mal e quem esqueceu o post-it.',
    cost: '1.7e18',
    effects: [{ stat: 'sprintReward', op: 'mult', value: 1.5 }],
    requires: [level('backlog-infinito', 5)],
  },
  {
    id: 'b1-design-tokens',
    professor: 'b1',
    name: 'Design Tokens',
    emoji: '🎨',
    description: 'Toda a produção e todo clique valem 15% mais. Uma cor, um nome, mil telas.',
    cost: '1.5e19',
    effects: [{ stat: 'globalPower', op: 'mult', value: 1.15 }],
    requires: [level('backlog-infinito', 15)],
  },

  // ---------------------------------------------------------------- Angelo: synergy and graduation
  {
    id: 'angelo-reuniao',
    professor: 'angelo',
    name: 'Reunião de Alinhamento',
    emoji: '🤝',
    description: 'Sinergia +2 pontos percentuais por professor contratado. Todo mundo alinhado em apenas três horas.',
    cost: '1.5e19',
    effects: [{ stat: 'synergy', op: 'add', value: 0.02 }],
    requires: [level('ata-de-reuniao', 5)],
  },
  {
    id: 'angelo-colegiado',
    professor: 'angelo',
    name: 'Colegiado de Curso',
    emoji: '🏛️',
    description: 'Sinergia +3 pontos percentuais por professor contratado. Decisão por maioria, almoço por unanimidade.',
    cost: '1.5e20',
    effects: [{ stat: 'synergy', op: 'add', value: 0.03 }],
    requires: [level('heranca-multipla', 5)],
  },
  {
    id: 'angelo-projeto-pedagogico',
    professor: 'angelo',
    name: 'Projeto Pedagógico',
    emoji: '📚',
    description: 'Disciplinas do Angelo x2 e sinergia +2 pontos. O documento que todo mundo cita e poucos releem.',
    cost: '1.5e21',
    effects: [
      { stat: 'prof:angelo', op: 'mult', value: 2 },
      { stat: 'synergy', op: 'add', value: 0.02 },
    ],
    requires: [level('polimorfismo', 5)],
  },
  {
    id: 'angelo-ceo',
    professor: 'angelo',
    name: 'Ceo',
    emoji: '💼',
    description: 'Formaturas rendem 25% mais diplomas. Visão estratégica e uma maleta bem grande.',
    cost: '1.5e22',
    effects: [{ stat: 'diplomaGain', op: 'mult', value: 1.25 }],
    requires: [level('polimorfismo', 15)],
  },
  {
    id: 'angelo-cerimonial',
    professor: 'angelo',
    name: 'Cerimonial',
    emoji: '🎓',
    description: 'Formaturas rendem mais 25% de diplomas. Com discurso do paraninfo e tudo.',
    cost: '1e23',
    effects: [{ stat: 'diplomaGain', op: 'mult', value: 1.25 }],
    requires: [level('polimorfismo', 25)],
  },

  // ---------------------------------------------------------------- Pablo: complexity
  {
    id: 'pablo-o1',
    professor: 'pablo',
    name: 'O(1) de Cabeça',
    emoji: '🧠',
    description: 'O custo cresce menos a cada nível (-0,01) e toda disciplina rende 50% mais. Ele já sabia a resposta antes da pergunta.',
    cost: '8e21',
    effects: [
      { stat: 'costGrowth', op: 'add', value: -0.01 },
      { stat: 'idlePower', op: 'mult', value: 1.5 },
    ],
    requires: [level('lista-encadeada', 5)],
  },
  {
    id: 'pablo-divisao-e-conquista',
    professor: 'pablo',
    name: 'Divisão e Conquista',
    emoji: '⚔️',
    description: 'O custo cresce menos a cada nível (-0,01) e as disciplinas do Pablo rendem x2. Dividiu o problema e a conta.',
    cost: '8e22',
    effects: [
      { stat: 'costGrowth', op: 'add', value: -0.01 },
      { stat: 'prof:pablo', op: 'mult', value: 2 },
    ],
    requires: [level('pilha-e-fila', 5)],
  },
  {
    id: 'pablo-programacao-dinamica',
    professor: 'pablo',
    name: 'Programação Dinâmica',
    emoji: '🧩',
    description: 'O custo cresce menos a cada nível (-0,01) e toda disciplina rende x2. Guardar o resultado para não pagar duas vezes.',
    cost: '8e23',
    effects: [
      { stat: 'costGrowth', op: 'add', value: -0.01 },
      { stat: 'idlePower', op: 'mult', value: 2 },
    ],
    requires: [level('grafo-caminho-minimo', 5)],
  },
  {
    id: 'pablo-big-o',
    professor: 'pablo',
    name: 'Big O',
    emoji: '📈',
    description: 'Libera a habilidade Big O (custos pela metade por 20 s). Precisa do Guto contratado. Tudo cresce, mas nada cresce mais rápido que o Pablo.',
    cost: '5e23',
    effects: [],
    requires: [level('pilha-e-fila', 15), { kind: 'professorHired', professor: 'guto' }],
    unlocksAbility: 'big-o',
  },
  {
    id: 'pablo-templo-da-complexidade',
    professor: 'pablo',
    name: 'Templo da Complexidade',
    emoji: '🛕',
    description: 'O custo cresce menos a cada nível (-0,01) e toda produção e clique valem x2. Aqui só se entra com prova formal.',
    cost: '1e25',
    effects: [
      { stat: 'costGrowth', op: 'add', value: -0.01 },
      { stat: 'globalPower', op: 'mult', value: 2 },
    ],
    requires: [level('grafo-caminho-minimo', 15)],
  },
  {
    id: 'pablo-arvore-balanceada',
    professor: 'pablo',
    name: 'Árvore Balanceada',
    emoji: '🌳',
    description: 'O custo cresce menos a cada nível (-0,01) e toda produção e clique valem x2. Altura mínima, ego proporcional.',
    cost: '1e26',
    effects: [
      { stat: 'costGrowth', op: 'add', value: -0.01 },
      { stat: 'globalPower', op: 'mult', value: 2 },
    ],
    requires: [level('grafo-caminho-minimo', 25)],
  },
];
