import type { ProfessorId, Rarity, SkinDef } from './types';

type SkinSeed = {
  id: string;
  name: string;
  rarity: Rarity;
  description: string;
  /** The skin has its own head, drawn wearing the headgear (heads/<skinId>). */
  headgear?: boolean;
  default?: boolean;
  palette: [string, string, string];
  artPrompt: string;
};

/** Builds a SkinDef from the compact rows below: body and head asset keys follow the skin id. */
const make = (professor: ProfessorId, seeds: SkinSeed[]): SkinDef[] =>
  seeds.map((seed) => ({
    id: seed.id,
    professor,
    name: seed.name,
    rarity: seed.rarity,
    description: seed.description,
    ...(seed.default ? { default: true } : {}),
    body: `skins/${seed.id}`,
    ...(seed.headgear ? { head: `heads/${seed.id}` } : {}),
    palette: { primary: seed.palette[0], secondary: seed.palette[1], accent: seed.palette[2] },
    artPrompt: seed.artPrompt,
  }));

/** The closed list of 46 skins (GAME_DESIGN section 6). Each non-default one is the reward of exactly one achievement. */
export const skins: SkinDef[] = [
  ...make('edecio', [
    {
      id: 'edecio-default',
      name: 'Polo Vermelha',
      rarity: 'common',
      description: 'Polo vermelha e jeans. O uniforme oficial de quem fala "muito legal".',
      default: true,
      palette: ['#d83a40', '#2f4f8f', '#f2f2f2'],
      artPrompt: 'red polo shirt, blue jeans, red sneakers',
    },
    {
      id: 'edecio-cafe',
      name: 'Café Quentinho',
      rarity: 'common',
      description: 'Avental de barista e uma caneca fumegante. A lógica rende mais depois do café.',
      palette: ['#6b4226', '#f1e4cf', '#e5484d'],
      artPrompt: 'brown barista apron over a white shirt, steaming coffee mug in one hand, dark trousers',
    },
    {
      id: 'edecio-programador',
      name: 'Programador',
      rarity: 'common',
      description: 'Moletom preto com capuz e notebook debaixo do braço. Funciona na máquina dele.',
      palette: ['#1d1d24', '#3a3a48', '#4ade80'],
      artPrompt: 'black hooded sweatshirt with the hood down, laptop tucked under one arm, dark jeans, sneakers',
    },
    {
      id: 'edecio-chad',
      name: 'Chad',
      rarity: 'rare',
      description: 'Regata, braços de academia e um halter. Levanta peso e levanta a turma.',
      palette: ['#e8d7b5', '#b8402f', '#3b3b44'],
      artPrompt: 'white tank top, big muscular arms holding a dumbbell, gym shorts, training shoes',
    },
    {
      id: 'edecio-cria',
      name: 'Cria',
      rarity: 'rare',
      description: 'Camisa de time, corrente dourada, bermuda e chinelo. Estilo de quem chegou agora no campus.',
      headgear: true,
      palette: ['#1f7a3d', '#f5c542', '#2a2a2a'],
      artPrompt: 'green football team jersey, thick gold chain, baggy shorts, flip-flops',
    },
    {
      id: 'edecio-prisioneiro',
      name: 'Prisioneiro',
      rarity: 'rare',
      description: 'Uniforme laranja com algema solta. Foi preso por excesso de sorrisos.',
      palette: ['#f08a1c', '#8a4d0f', '#9aa0aa'],
      artPrompt: 'bright orange prison jumpsuit with a loose open handcuff dangling from one wrist, orange pants',
    },
    {
      id: 'edecio-atleta',
      name: 'Atleta',
      rarity: 'rare',
      description: 'Uniforme de futebol e uma bola no pé. Joga a lógica com as duas pernas.',
      palette: ['#f2f2f2', '#2a6edb', '#f5c542'],
      artPrompt: 'white and blue football kit with shorts and long socks, football boots, soccer ball at his feet',
    },
    {
      id: 'edecio-full-dima',
      name: 'Full Dima',
      rarity: 'epic',
      description: 'Armadura de blocos azul-diamante e espada de blocos. Cada nível é uma picareta nova.',
      headgear: true,
      palette: ['#2ec4d6', '#1f6f86', '#e9fbff'],
      artPrompt: 'blocky voxel diamond armor in cyan and teal, chest plate and boots made of cubes, blocky diamond sword',
    },
    {
      id: 'edecio-ceo',
      name: 'CEO',
      rarity: 'epic',
      description: 'Terno escuro, gravata vermelha e maleta. Reunião marcada para agora.',
      palette: ['#23232e', '#e5484d', '#cfd3da'],
      artPrompt: 'dark charcoal business suit, red tie, white shirt, polished black shoes, black briefcase in hand',
    },
    {
      id: 'edecio-gladiador',
      name: 'Gladiador',
      rarity: 'epic',
      description: 'Armadura romana, capa vermelha e gládio. Ave, aluno: os que vão aprender te saúdam.',
      headgear: true,
      palette: ['#b8402f', '#c9a227', '#6b4a2b'],
      artPrompt: 'Roman gladiator armor with bronze chest plate, red cape, leather skirt strips, sandals, short sword in hand',
    },
    {
      id: 'edecio-samurai',
      name: 'Samurai',
      rarity: 'legendary',
      description: 'Armadura samurai azul-petróleo e katana. Um corte só, um sorriso só.',
      headgear: true,
      palette: ['#1f5f6b', '#d7b44a', '#15212a'],
      artPrompt: 'deep teal samurai armor with gold trim, shoulder plates, katana at the hip, dark hakama pants, sandals',
    },
  ]),
  ...make('gladimir', [
    {
      id: 'gladimir-default',
      name: 'Xadrez de Sempre',
      rarity: 'common',
      description: 'Camisa xadrez, calça cáqui e crachá. O look de quem vive em servidor.',
      default: true,
      palette: ['#3b82f6', '#c2a878', '#f2f2f2'],
      artPrompt: 'blue plaid flannel shirt, khaki trousers, id badge on a lanyard, brown shoes',
    },
    {
      id: 'gladimir-dba',
      name: 'DBA de Plantão',
      rarity: 'common',
      description: 'Colete, cabo de rede no ombro e caneca "SELECT *". Plantão de fim de semana, com bom humor.',
      palette: ['#2d3a52', '#e3e7ee', '#f0b429'],
      artPrompt: 'navy utility vest over a grey shirt, coiled network cable over one shoulder, mug printed with SELECT *, dark trousers',
    },
    {
      id: 'gladimir-maker',
      name: 'Maker IoT',
      rarity: 'rare',
      description: 'Jaleco com sensores e LEDs, protoboard na mão e óculos de proteção. Solda antes de perguntar.',
      headgear: true,
      palette: ['#f2f2f2', '#2ec27e', '#3b82f6'],
      artPrompt: 'white lab coat covered in small sensors and blinking LEDs, holding a breadboard with wires, jeans, sneakers',
    },
    {
      id: 'gladimir-piloto',
      name: 'Piloto Rebelde',
      rarity: 'epic',
      description: 'Macacão laranja de piloto espacial e colete branco. Decola antes de o café esfriar.',
      headgear: true,
      palette: ['#f08a1c', '#f2f2f2', '#2a3a5c'],
      artPrompt: 'orange space pilot flight suit with a white vest, utility belt, tall dark boots, no helmet',
    },
    {
      id: 'gladimir-mestre',
      name: 'Mestre da Galáxia',
      rarity: 'legendary',
      description: 'Túnica bege de cavaleiro espacial e sabre de luz azul. Que o JOIN esteja com você.',
      headgear: true,
      palette: ['#d9c7a0', '#6b5a3c', '#4aa8ff'],
      artPrompt: 'beige space knight robe tunic with a brown belt, glowing blue energy sword held in one hand, brown boots',
    },
  ]),
  ...make('b2', [
    {
      id: 'b2-default',
      name: 'Blazer Rosa',
      rarity: 'common',
      description: 'Blazer rosa, camiseta branca e calça preta. Combina com todos os botões.',
      default: true,
      palette: ['#ec4899', '#f2f2f2', '#22222a'],
      artPrompt: 'pink blazer over a white t-shirt, black trousers, white sneakers',
    },
    {
      id: 'b2-postit',
      name: 'Mural de Post-its',
      rarity: 'common',
      description: 'Roupa coberta de post-its coloridos e uma caneta na mão. Cada ideia tem a sua cor.',
      palette: ['#f6e05e', '#f472b6', '#60a5fa'],
      artPrompt: 'outfit covered with colorful sticky notes in yellow, pink and blue, marker pen in hand, plain trousers',
    },
    {
      id: 'b2-wireframe',
      name: 'Wireframe',
      rarity: 'rare',
      description: 'Roupa cinza com caixas e X de wireframe. Tudo é rascunho até aprovarem.',
      palette: ['#b8bcc6', '#6b7280', '#ec4899'],
      artPrompt: 'flat grey outfit drawn like a UI wireframe, boxes with crossed diagonal lines and placeholder rectangles, grey shoes',
    },
    {
      id: 'b2-darkmode',
      name: 'Dark Mode',
      rarity: 'epic',
      description: 'Toda de preto com detalhes neon roxos. Seus olhos agradecem à noite.',
      palette: ['#14141c', '#a855f7', '#22d3ee'],
      artPrompt: 'all black outfit with glowing neon purple trim and piping, black boots with neon soles',
    },
    {
      id: 'b2-paleta',
      name: 'Paleta Viva',
      rarity: 'legendary',
      description: 'Vestido em degradê arco-íris e pincel gigante. Nenhuma cor ficou de fora.',
      palette: ['#ec4899', '#facc15', '#38bdf8'],
      artPrompt: 'knee-length dress with a rainbow gradient from red to violet, holding a giant paintbrush, colorful shoes',
    },
  ]),
  ...make('wagner', [
    {
      id: 'wagner-default',
      name: 'Preto Básico',
      rarity: 'common',
      description: 'Camiseta preta, calça cargo e crachá. Discreto como um bom firewall.',
      default: true,
      palette: ['#1f1f26', '#4b5563', '#22c55e'],
      artPrompt: 'plain black t-shirt, olive cargo trousers, id badge on a lanyard, black sneakers',
    },
    {
      id: 'wagner-hacker',
      name: 'Capuz Verde',
      rarity: 'common',
      description: 'Moletom com capuz e código verde, notebook em mãos. Só invade com autorização.',
      palette: ['#101614', '#22c55e', '#9ca3af'],
      artPrompt: 'dark hooded sweatshirt with glowing green code characters printed on it, hood down, laptop in hand, dark jeans',
    },
    {
      id: 'wagner-agente',
      name: 'Agente Secreto',
      rarity: 'rare',
      description: 'Terno preto, gravata fina e fone espiral. Missão: trocar a senha do laboratório.',
      headgear: true,
      palette: ['#16161c', '#e5e7eb', '#ef4444'],
      artPrompt: 'slim black suit, thin black tie, white shirt, coiled earpiece cable, polished black shoes',
    },
    {
      id: 'wagner-firewall',
      name: 'Firewall',
      rarity: 'epic',
      description: 'Armadura de tijolos com chamas laranja. Aqui ninguém passa sem pedir.',
      palette: ['#b04a2f', '#f08a1c', '#3a2a24'],
      artPrompt: 'armor built from red bricks like a brick wall, orange flames licking up the edges, brick gauntlets and boots',
    },
    {
      id: 'wagner-cripto',
      name: 'Cavaleiro da Criptografia',
      rarity: 'legendary',
      description: 'Armadura prateada com cadeado no peito e escudo com chave. Só abre com a chave certa.',
      headgear: true,
      palette: ['#c7ccd6', '#22c55e', '#f5c542'],
      artPrompt: 'shining silver knight armor with a big padlock emblem on the chest plate, shield decorated with a golden key, steel boots',
    },
  ]),
  ...make('guto', [
    {
      id: 'guto-default',
      name: 'Camisa Florida',
      rarity: 'common',
      description: 'Camisa havaiana, bermuda e chinelo. Sempre pronto para a resenha.',
      default: true,
      palette: ['#22b8cf', '#f59e0b', '#f2f2f2'],
      artPrompt: 'Hawaiian floral shirt in teal and orange, board shorts, flip-flops',
    },
    {
      id: 'guto-churrasqueiro',
      name: 'Mestre do Churrasco',
      rarity: 'common',
      description: 'Avental, espeto na mão e pano no ombro. O ponto da carne e o ponto do deploy.',
      palette: ['#8a3b2a', '#f1e4cf', '#3b3b44'],
      artPrompt: 'red barbecue apron, skewer of meat in one hand, dish towel over one shoulder, shorts, sandals',
    },
    {
      id: 'guto-pagodeiro',
      name: 'Pagodeiro',
      rarity: 'rare',
      description: 'Camisa aberta, pandeiro na mão e chapéu panamá. Segunda-feira ainda não existe.',
      headgear: true,
      palette: ['#f5e6c8', '#2f9e8f', '#e07a1f'],
      artPrompt: 'open linen shirt over a white t-shirt, light trousers, loafers, holding a tambourine',
    },
    {
      id: 'guto-dj',
      name: 'DJ do Deploy',
      rarity: 'epic',
      description: 'Jaqueta neon, fones no pescoço e controladora. Cada subida para produção tem trilha sonora.',
      palette: ['#7c3aed', '#22d3ee', '#f472b6'],
      artPrompt: 'neon glowing jacket in purple and cyan, headphones around the neck, holding a small DJ controller, dark pants',
    },
    {
      id: 'guto-astronauta',
      name: 'Astronauta da Nuvem',
      rarity: 'legendary',
      description: 'Traje espacial branco com nuvens azuis. A nuvem agora é literal.',
      headgear: true,
      palette: ['#f2f4f8', '#38bdf8', '#06b6d4'],
      artPrompt: 'white space suit decorated with blue cloud patches and a cloud logo on the chest, gloves, chunky space boots',
    },
  ]),
  ...make('b1', [
    {
      id: 'b1-default',
      name: 'Listras e Jeans',
      rarity: 'common',
      description: 'Camiseta listrada e jaqueta jeans. Prática para dias de sprint.',
      default: true,
      palette: ['#a855f7', '#4a6fa5', '#f2f2f2'],
      artPrompt: 'striped t-shirt in white and purple, denim jacket, blue jeans, white sneakers',
    },
    {
      id: 'b1-po',
      name: 'Product Owner',
      rarity: 'common',
      description: 'Blazer e um quadro kanban debaixo do braço. A prioridade é sempre a próxima.',
      palette: ['#5b3a8c', '#e9d5ff', '#f59e0b'],
      artPrompt: 'purple blazer over a light shirt, small kanban board with sticky note columns tucked under one arm, dark trousers',
    },
    {
      id: 'b1-flexbox',
      name: 'Flexbox',
      rarity: 'rare',
      description: 'Roupa com blocos coloridos perfeitamente alinhados. Centralizou sem esforço.',
      palette: ['#a855f7', '#22d3ee', '#facc15'],
      artPrompt: 'outfit made of neat aligned colored rectangular blocks in a row, evenly spaced like a CSS flex layout, matching boots',
    },
    {
      id: 'b1-lancamento',
      name: 'Dia de Lançamento',
      rarity: 'epic',
      description: 'Macacão roxo de astronauta com foguete nas costas. Hoje vai ao ar.',
      palette: ['#7c3aed', '#f2f2f2', '#f97316'],
      artPrompt: 'purple astronaut jumpsuit with a small rocket backpack and flame, white patches, grey boots',
    },
    {
      id: 'b1-rainha',
      name: 'Rainha do CSS',
      rarity: 'legendary',
      description: 'Vestido roxo com capa e cetro de chaves { }. Seu reino tem estilo.',
      headgear: true,
      palette: ['#7c3aed', '#facc15', '#f2f2f2'],
      artPrompt: 'long purple royal dress with a flowing cape, golden scepter topped with curly braces { }, jeweled belt',
    },
  ]),
  ...make('angelo', [
    {
      id: 'angelo-default',
      name: 'Social e Gravata',
      rarity: 'common',
      description: 'Camisa social, gravata e calça social. A coordenação sempre presente.',
      default: true,
      palette: ['#f2f2f2', '#b45309', '#3b3b4a'],
      artPrompt: 'white dress shirt with rolled sleeves, amber tie, grey dress trousers, black leather shoes',
    },
    {
      id: 'angelo-terno',
      name: 'Terno de Reunião',
      rarity: 'common',
      description: 'Terno completo e pasta de documentos. A reunião começa no horário (às vezes).',
      palette: ['#2f3a4f', '#f59e0b', '#e5e7eb'],
      artPrompt: 'full navy business suit with amber pocket square, white shirt, holding a leather document folder, black shoes',
    },
    {
      id: 'angelo-maestro',
      name: 'Maestro',
      rarity: 'rare',
      description: 'Fraque e batuta na mão. Rege o semestre inteiro sem perder o compasso.',
      palette: ['#15151c', '#f2f2f2', '#f59e0b'],
      artPrompt: 'black tailcoat with white bow tie and shirt, striped trousers, holding a conductor baton, black shoes',
    },
    {
      id: 'angelo-paraninfo',
      name: 'Paraninfo',
      rarity: 'epic',
      description: 'Beca preta de formatura com faixa âmbar e canudo na mão. Discurso de cinco minutos (dez).',
      headgear: true,
      palette: ['#1a1a22', '#f59e0b', '#e5e7eb'],
      artPrompt: 'black graduation gown with an amber sash across the chest, rolled diploma tied with a ribbon in hand, black shoes',
    },
    {
      id: 'angelo-rei',
      name: 'Herança Real',
      rarity: 'legendary',
      description: 'Manto real vermelho com arminho e cetro. A herança é múltipla e a coroa é só uma.',
      headgear: true,
      palette: ['#b91c1c', '#f5c542', '#f5f5f4'],
      artPrompt: 'royal red velvet robe with white ermine fur trim, golden scepter in hand, ornate golden clasp, dark boots',
    },
  ]),
  ...make('pablo', [
    {
      id: 'pablo-default',
      name: 'Suéter e Camisa',
      rarity: 'common',
      description: 'Suéter azul sobre camisa branca. Elegante e, claro, calculado.',
      default: true,
      palette: ['#4f46e5', '#f2f2f2', '#3b3b4a'],
      artPrompt: 'blue knit sweater over a white collared shirt, dark trousers, brown loafers',
    },
    {
      id: 'pablo-cientista',
      name: 'Cientista',
      rarity: 'common',
      description: 'Jaleco branco e prancheta com fórmulas. Toda hipótese merece um bom experimento.',
      palette: ['#f2f4f8', '#6366f1', '#94a3b8'],
      artPrompt: 'white lab coat over a blue shirt, clipboard covered with math formulas, dark trousers, sneakers',
    },
    {
      id: 'pablo-enxadrista',
      name: 'Enxadrista',
      rarity: 'rare',
      description: 'Colete xadrez e uma peça de rei na mão. Já está três jogadas à frente.',
      palette: ['#1f1f2b', '#e5e7eb', '#6366f1'],
      artPrompt: 'black and white checkered vest over a white shirt, holding a chess king piece, dark trousers, dress shoes',
    },
    {
      id: 'pablo-mago',
      name: 'Mago dos Algoritmos',
      rarity: 'epic',
      description: 'Manto azul com estrelas e cajado com árvore binária. Complexidade logarítmica, magia pura.',
      headgear: true,
      palette: ['#2f2a8f', '#facc15', '#6366f1'],
      artPrompt: 'long blue wizard robe covered in yellow stars, wooden staff topped with a small binary tree of glowing nodes, pointed shoes',
    },
    {
      id: 'pablo-galactico',
      name: 'Cérebro Galáctico',
      rarity: 'legendary',
      description: 'Traje cósmico brilhante com aura de estrelas. O universo cabe em uma linha de código.',
      palette: ['#3b2f9e', '#8b5cf6', '#fde68a'],
      artPrompt: 'shimmering cosmic bodysuit with a galaxy and starfield pattern, glowing star aura around the body, glowing boots',
    },
  ]),
];
