import type { SprintDef } from './types';

/** Short goals with a deadline (Bruna B1's layer). The ones that need another layer carry `requires`. */
export const sprints: SprintDef[] = [
  {
    id: 'aquecimento',
    name: 'Aquecimento',
    emoji: '🔥',
    description: 'Dê 60 cliques em 60 s. Dedo quente, cartão movido.',
    goal: { kind: 'clicks', amount: 60 },
    durationMs: 60_000,
    reward: { kind: 'coins', seconds: 60 },
    requires: [],
  },
  {
    id: 'maratona-de-cliques',
    name: 'Maratona de Cliques',
    emoji: '🏃',
    description: 'Dê 200 cliques em 2 min. Respire entre um clique e outro.',
    goal: { kind: 'clicks', amount: 200 },
    durationMs: 120_000,
    reward: { kind: 'coins', seconds: 180 },
    requires: [],
  },
  {
    id: 'martelada',
    name: 'Martelada',
    emoji: '🔨',
    description: 'Dê 400 cliques em 2 min 30 s. Recompensa: produção x7 por 30 s.',
    goal: { kind: 'clicks', amount: 400 },
    durationMs: 150_000,
    reward: {
      kind: 'buff',
      buff: {
        id: 'buff-sprint-production',
        name: 'Sprint Concluída',
        emoji: '🏁',
        durationMs: 30_000,
        effects: [{ stat: 'idlePower', op: 'mult', value: 7 }],
      },
    },
    requires: [],
  },
  {
    id: 'dia-de-sorte',
    name: 'Dia de Sorte',
    emoji: '🍀',
    description: 'Acerte 3 críticos em 90 s. Ninguém prometeu que seria justo.',
    goal: { kind: 'crits', amount: 3 },
    durationMs: 90_000,
    reward: { kind: 'coins', seconds: 120 },
    requires: [{ kind: 'professorHired', professor: 'edecio' }],
  },
  {
    id: 'chuva-de-joinhas',
    name: 'Chuva de Joinhas',
    emoji: '👍',
    description: 'Acerte 10 críticos em 3 min. Recompensa: clique x10 por 15 s.',
    goal: { kind: 'crits', amount: 10 },
    durationMs: 180_000,
    reward: {
      kind: 'buff',
      buff: {
        id: 'buff-sprint-click',
        name: 'Joinha em Dobro',
        emoji: '👍',
        durationMs: 15_000,
        effects: [{ stat: 'clickPower', op: 'mult', value: 10 }],
      },
    },
    requires: [{ kind: 'professorHired', professor: 'edecio' }],
  },
  {
    id: 'combo-perfeito',
    name: 'Combo Perfeito',
    emoji: '🎯',
    description: 'Chegue a um combo de 10 passos em 60 s. É só não parar de clicar.',
    goal: { kind: 'reachCombo', amount: 10 },
    durationMs: 60_000,
    reward: { kind: 'coins', seconds: 90 },
    requires: [{ kind: 'professorHired', professor: 'edecio' }],
  },
  {
    id: 'combo-no-talo',
    name: 'Combo no Talo',
    emoji: '💥',
    description: 'Chegue a um combo de 20 passos em 90 s. A janela de 1,5 s é curta, mas honesta.',
    goal: { kind: 'reachCombo', amount: 20 },
    durationMs: 90_000,
    reward: { kind: 'coins', seconds: 240 },
    requires: [{ kind: 'professorHired', professor: 'edecio' }],
  },
  {
    id: 'dia-de-compras',
    name: 'Dia de Compras',
    emoji: '🛒',
    description: 'Compre 10 níveis de disciplinas ou upgrades em 90 s. Edécoin parado não rende.',
    goal: { kind: 'buyLevels', amount: 10 },
    durationMs: 90_000,
    reward: { kind: 'coins', seconds: 100 },
    requires: [],
  },
  {
    id: 'matricula-em-massa',
    name: 'Matrícula em Massa',
    emoji: '📝',
    description: 'Compre 30 níveis em 2 min 30 s. Recompensa: produção x7 por 30 s.',
    goal: { kind: 'buyLevels', amount: 30 },
    durationMs: 150_000,
    reward: {
      kind: 'buff',
      buff: {
        id: 'buff-sprint-enrollment',
        name: 'Turma Cheia',
        emoji: '🎒',
        durationMs: 30_000,
        effects: [{ stat: 'idlePower', op: 'mult', value: 7 }],
      },
    },
    requires: [],
  },
  {
    id: 'plantao-de-seguranca',
    name: 'Plantão de Segurança',
    emoji: '🛡️',
    description: 'Defenda 1 invasão em 2 min. Fique de olho no palco.',
    goal: { kind: 'defendEvents', amount: 1 },
    durationMs: 120_000,
    reward: { kind: 'coins', seconds: 150 },
    requires: [{ kind: 'professorHired', professor: 'wagner' }],
  },
  {
    id: 'ronda-completa',
    name: 'Ronda Completa',
    emoji: '🚨',
    description: 'Defenda 3 invasões em 3 min. Cada alerta conta.',
    goal: { kind: 'defendEvents', amount: 3 },
    durationMs: 180_000,
    reward: { kind: 'coins', seconds: 400 },
    requires: [{ kind: 'professorHired', professor: 'wagner' }],
  },
  {
    id: 'fechamento-do-mes',
    name: 'Fechamento do Mês',
    emoji: '💰',
    description: 'Ganhe o equivalente a 70 s de produção em 60 s. Clicar ajuda a passar da meta.',
    goal: { kind: 'earnSeconds', amount: 70 },
    durationMs: 60_000,
    reward: { kind: 'coins', seconds: 100 },
    requires: [],
  },
  {
    id: 'fechamento-do-semestre',
    name: 'Fechamento do Semestre',
    emoji: '📊',
    description: 'Ganhe o equivalente a 250 s de produção em 3 min. Só a produção parada não dá conta.',
    goal: { kind: 'earnSeconds', amount: 250 },
    durationMs: 180_000,
    reward: { kind: 'coins', seconds: 500 },
    requires: [],
  },
];
