// Rewrites src/ui/art/manifest.ts from the PNGs in public/assets (+ art/anchors.json).
import fs from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';
import { ASSETS_DIR, ANCHORS_FILE, MANIFEST_FILE, readJson } from './lib.mjs';

const HEADER = `/**
 * Generated by \`npm run art:manifest\` from the PNG files in public/assets. Do not edit by hand.
 *
 * Keys are paths relative to public/assets without extension ("skins/edecio-samurai"),
 * so the file is served at \`/assets/<key>.png\`. A key that is missing here means the
 * art does not exist yet and the UI must draw its procedural fallback.
 */

export interface SpriteMeta {
  /** Native size in pixels. Draw at an integer multiple with image-rendering: pixelated. */
  w: number;
  h: number;
  /**
   * Attachment point in native pixels, from the top-left corner.
   * - skins/*: the neck, where the head's chin sits.
   * - heads/*: the chin, which sits on the body's neck.
   * - hats/*: the point of the hat that rests on the top of the head.
   */
  anchor?: { x: number; y: number };
}
`;

function walk(dir) {
  const out = [];
  if (!fs.existsSync(dir)) return out;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...walk(p));
    else if (e.name.toLowerCase().endsWith('.png')) out.push(p);
  }
  return out;
}

const anchors = readJson(ANCHORS_FILE, {});
const entries = [];
for (const file of walk(ASSETS_DIR)) {
  const key = path.relative(ASSETS_DIR, file).split(path.sep).join('/').replace(/\.png$/i, '');
  const { width, height } = await sharp(file).metadata();
  const a = anchors[key];
  entries.push({ key, w: width, h: height, anchor: a });
}
entries.sort((a, b) => a.key.localeCompare(b.key));

const body = entries.length
  ? entries
      .map((e) => `  ${JSON.stringify(e.key)}: { w: ${e.w}, h: ${e.h}${e.anchor ? `, anchor: { x: ${e.anchor.x}, y: ${e.anchor.y} }` : ''} },`)
      .join('\n')
  : '';
const ts = `${HEADER}\nexport const ASSETS: Record<string, SpriteMeta> = {${body ? '\n' + body + '\n' : ''}};\n`;
fs.mkdirSync(path.dirname(MANIFEST_FILE), { recursive: true });
fs.writeFileSync(MANIFEST_FILE, ts);
console.log(`manifest: ${entries.length} assets -> ${path.relative(process.cwd(), MANIFEST_FILE)}`);
